# ===== Matrix Authentication =====
# The Matrix homeserver to connect to
homeserver: https://matrix.example.com
# The Matrix username to log in as. This should be your account, as the bot
# will post on your behalf.
username: "@username:example.com"
# A file containing the Matrix user password
password_file: /path/to/password/file
