name: Go

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.17]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install goimports
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          export PATH="$HOME/go/bin:$PATH"
        if: matrix.go-version == 1.17

      - name: Install pre-commit
        run: pip install pre-commit
        if: matrix.go-version == 1.17

      - name: Lint
        run: pre-commit run -a
        if: matrix.go-version == 1.17

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.16, 1.17]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install libolm
        run: sudo apt-get install libolm-dev libolm3

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
