name: Go

on: [push, pull_request]

env:
  GO_VERSION: "1.20"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install honnef.co/go/tools/cmd/staticcheck@v0.3.3
          export PATH="$HOME/go/bin:$PATH"

          sudo apt-get install libolm-dev libolm3


      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.16, 1.17]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install libolm
        run: sudo apt-get install libolm-dev libolm3

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
